### ISSUE TITLE
编译好jar包以后怎么启动项目

### ISSUE THREAD

**Issue by yikela1990** [970263611/redis-x#1]
mvn编译好以后生成jar包：./target/redis-x-jar-with-dependencies.jar 

直接jar -jar 运行报错
$ java -jar ./target/redis-x-jar-with-dependencies.jar 
2024-06-28T12:02:59.799Z main ERROR appender RollingFile has no parameter that matches element ThresholdFilter

**Comment by 970263611** [comment]
这个错误忽略即可，这个是日志方面的，不影响功能。没有其他日志是因为日志级别过高，调整成Trace。你有其他问题随时在issue里面提交即可，希望你有一个愉快的使用体验。

**Comment by 970263611** [comment]
日志的错误输出问题已经修复，请更新代码重新编译运行

**Comment by yikela1990** [comment]
更新完代码，编译后重新运行，怎么刷这么多日志？
命令：
java -jar ./target/redis-x-jar-with-dependencies.jar

日志：
![图片](https://github.com/970263611/redis-x/assets/76995384/6756fdb9-702b-4689-8e99-34edd622d5f0)

**Comment by 970263611** [comment]
因为现在的默认日志级别为Trace，如果需要调控日志数量，请编辑log4j.xml
