### ISSUE TITLE
全量同步阶段怎么限制并发

### ISSUE THREAD

**Issue by yikela1990** [970263611/redis-x#10]
全量阶段把源端节点打挂了，怎么限制并发？

**Comment by yikela1990** [comment]
是执行bgsave吗

**Comment by 970263611** [comment]
对了，如果您觉得redis-x好用，可否给点个赞

**Comment by yikela1990** [comment]
如果是源端内存不够的情况怎么避免源节点挂掉？

**Comment by 970263611** [comment]
这个问题应该考虑源节点扩容，不应该在redis-x这面做操作

**Comment by 970263611** [comment]
这个问题关闭了哈，还有我们还是期望你觉得redis-x好用的时候能点个赞，谢谢
