### ISSUE TITLE
配置文件怎么拿出来运行？

### ISSUE THREAD

**Issue by yikela1990** [970263611/redis-x#2]
目前我看配置文件是在 src/main/resources/redisx.yml，怎么编译好jar包以后，把配置文件拿出来运行？

**Comment by 970263611** [comment]
目前没开发此功能，请关注后续版本，大概今天或明天会加上

**Comment by 970263611** [comment]
指定配置文件启动功能已经添加到main分支，请关注，使用方式为java -jar xxx redisx.yml，后续我会将补充到readme中
